# 配置文件不同于配置类
# 配置文件一般用于保存需要修改的配置值
# 测试自定义的外部配置文件读取
test:
  message: Test!
  id: 1
  name: TestName
  age: 18
  sex: 男
  email: test@test.com

# 配置文件中的值可以通过 @Value 注解获取
# 常见配置项如下
# 这些配置都是 Starter 提供的，可以根据需要修改，也可以使用默认值，极大的方便了开发
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: oddy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    # 配置静态资源访问路径，默认是 /**，若规定访问时使用 http:网址/static/xx
    # 默认的静态资源应放在 resources/static/static/ 下，
    # 修改后静态资源放在 resources/static/ 下即可
    static-path-pattern: /static/**
    #  security:
    # 配置默认用户信息
  #    user:
  #      name: dev
  #      password: dev
  #      roles:
  #        - admin
  #        - user
  mail:
    host: smtp.exmail.qq.com
    username: xxxxxx
    password: xxxxxx
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  jpa:
    # 打开日志
    show-sql: true
    hibernate:
      # 检查数据库的表结构，没有时会自动创建，生产环境不推荐打开
      ddl-auto: update

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*' # 使用 '* 暴露全部接口
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  # 开放 info 接口下的信息展示
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

mybatis-plus:
  configuration:
    # 开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
